// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jogos.Persistence;

namespace Jogos.Persistence.Migrations
{
    [DbContext(typeof(JogosContext))]
    [Migration("20230421212204_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Jogos.Domain.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Jogos.Domain.JogoGenero", b =>
                {
                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JogoId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.ToTable("JogosGeneros");
                });

            modelBuilder.Entity("jogos.Domain.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desenvolvedora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("Jogos.Domain.JogoGenero", b =>
                {
                    b.HasOne("Jogos.Domain.Genero", "Genero")
                        .WithMany("JogosGeneros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("jogos.Domain.Models.Jogo", "Jogo")
                        .WithMany("JogosGeneros")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("Jogos.Domain.Genero", b =>
                {
                    b.Navigation("JogosGeneros");
                });

            modelBuilder.Entity("jogos.Domain.Models.Jogo", b =>
                {
                    b.Navigation("JogosGeneros");
                });
#pragma warning restore 612, 618
        }
    }
}
